### ISSUE TITLE
Plugin Fails to Load on 1.21.3

### ISSUE THREAD

**Issue by ItsSchatten** [Moulberry/AxiomPaperPlugin#32]
```
[17:00:43 ERROR]: Error occurred while enabling AxiomPaper v4.0.1 (Is it up to date?)
java.lang.NoSuchMethodError: 'net.minecraft.world.level.block.state.BlockState net.minecraft.world.level.block.Block.o()'
	at AxiomPaper-4.0.1-for-MC1.21.1.jar/com.moulberry.axiom.buffer.BlockBuffer.<clinit>(BlockBuffer.java:23) ~[AxiomPaper-4.0.1-for-MC1.21.1.jar:?]
	at AxiomPaper-4.0.1-for-MC1.21.1.jar/com.moulberry.axiom.DisallowedBlocks.createAllowedBlockRegistry(DisallowedBlocks.java:89) ~[AxiomPaper-4.0.1-for-MC1.21.1.jar:?]
	at AxiomPaper-4.0.1-for-MC1.21.1.jar/com.moulberry.axiom.AxiomPaper.onEnable(AxiomPaper.java:89) ~[AxiomPaper-4.0.1-for-MC1.21.1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.3.jar:1.21.3-23-59b79c8]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.3.jar:1.21.3-23-59b79c8]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:643) ~[paper-1.21.3.jar:1.21.3-23-59b79c8]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:592) ~[paper-1.21.3.jar:1.21.3-23-59b79c8]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:767) ~[paper-1.21.3.jar:1.21.3-23-59b79c8]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:529) ~[paper-1.21.3.jar:1.21.3-23-59b79c8]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:326) ~[paper-1.21.3.jar:1.21.3-23-59b79c8]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1233) ~[paper-1.21.3.jar:1.21.3-23-59b79c8]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:339) ~[paper-1.21.3.jar:1.21.3-23-59b79c8]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by Moulberry** [comment]
Your plugin jar says 1.21.1. It will not work in 1.21.3

**Comment by ItsSchatten** [comment]
That I understand, perhaps the better wording would have been a request for an update to 1.21.3.

Building from `master` locally still produced the same error.
```
[16:28:33 ERROR]: Error occurred while enabling AxiomPaper v4.0.2 (Is it up to date?)
java.lang.NoSuchMethodError: 'net.minecraft.world.level.block.state.BlockState net.minecraft.world.level.block.Block.o()'
        at AxiomPaper-4.0.2.jar/com.moulberry.axiom.buffer.BlockBuffer.<clinit>(BlockBuffer.java:23) ~[AxiomPaper-4.0.2.jar:?]
        at AxiomPaper-4.0.2.jar/com.moulberry.axiom.DisallowedBlocks.createAllowedBlockRegistry(DisallowedBlocks.java:89) ~[AxiomPaper-4.0.2.jar:?]
        at AxiomPaper-4.0.2.jar/com.moulberry.axiom.AxiomPaper.onEnable(AxiomPaper.java:107) ~[AxiomPaper-4.0.2.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.3.jar:1.21.3-27-661839e]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.3.jar:1.21.3-27-661839e]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:643) ~[paper-1.21.3.jar:1.21.3-27-661839e]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:592) ~[paper-1.21.3.jar:1.21.3-27-661839e]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:767) ~[paper-1.21.3.jar:1.21.3-27-661839e]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:529) ~[paper-1.21.3.jar:1.21.3-27-661839e]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:326) ~[paper-1.21.3.jar:1.21.3-27-661839e]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1233) ~[paper-1.21.3.jar:1.21.3-27-661839e]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:339) ~[paper-1.21.3.jar:1.21.3-27-661839e]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

 And the server's version information as I forgot to include that in the main post:
 ```
[16:30:54 INFO]: Checking version, please wait...
[16:30:55 INFO]: This server is running Paper version 1.21.3-27-master@661839e (2024-11-11T19:22:47Z) (Implementing API version 1.21.3-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.3-23-59b79c8 (MC: 1.21.3)
```
